version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: terminbuchung
      MYSQL_USER: root
      MYSQL_PASSWORD: admin   
    ports:
      - "3307:3306"









   


